services:
  - type: web
    name: app
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: /data/app.db
