const fs = require('fs')
const prettier = require('prettier')

const tokens = require('../app/styles/tokens.json')

async function generateProps() {
  console.log('Regenerating app/styles/tokens.css...')

  let css = `
    /* This file is generated by \`scripts/watch-tokens.cjs\`. */
    /* Edit ~/styles/token.json and run \`npm run dev:tokens\` to update. */

    :root {
  `

  for (const [category, values] of Object.entries(tokens)) {
    for (const [name, value] of Object.entries(values)) {
      css += `--${category}-${name}: ${value};`
    }
  }

  css += '}'

  css = await prettier.format(css, { parser: 'css' })

  fs.writeFileSync('./app/styles/base/tokens.css', css)
}

generateProps()
